# Generated by Django 4.0.5 on 2022-06-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_producto_alter_usuario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audifonos',
            fields=[
                ('idAudifonos', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Audifonos')),
                ('nombreAudifonos', models.CharField(max_length=50, verbose_name='Nombre de Audifonos')),
                ('imagenAudifonos', models.CharField(max_length=150, verbose_name='Imagen de Audifonos')),
                ('precioAudifonos', models.IntegerField(verbose_name='Precio de Audifonos')),
                ('stockAudifonos', models.IntegerField(verbose_name='Stock de Audifonos')),
            ],
        ),
        migrations.CreateModel(
            name='Microfonos',
            fields=[
                ('idMicrofonos', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Microfonos')),
                ('nombreMicrofonos', models.CharField(max_length=50, verbose_name='Nombre de Microfonos')),
                ('imagenMicrofonos', models.CharField(max_length=150, verbose_name='Imagen de Microfonos')),
                ('precioMicrofonos', models.IntegerField(verbose_name='Precio de Microfonos')),
                ('stockMicrofonos', models.IntegerField(verbose_name='Stock de Microfonos')),
            ],
        ),
        migrations.CreateModel(
            name='Pilas',
            fields=[
                ('idPilas', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Pilas')),
                ('nombrePilas', models.CharField(max_length=50, verbose_name='Nombre de Pilas')),
                ('imagenPilas', models.CharField(max_length=150, verbose_name='Imagen de Pilas')),
                ('precioPilas', models.IntegerField(verbose_name='Precio de Pilas')),
                ('stockPilas', models.IntegerField(verbose_name='Stock de Pilas')),
            ],
        ),
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('idReloj', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Reloj')),
                ('nombreAReloj', models.CharField(max_length=50, verbose_name='Nombre del Reloj')),
                ('imagenReloj', models.CharField(max_length=150, verbose_name='Imagen del Reloj')),
                ('precioReloj', models.IntegerField(verbose_name='Precio del Reloj')),
                ('stockReloj', models.IntegerField(verbose_name='Stock del Reloj')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
