# Generated by Django 4.0.5 on 2022-06-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_audifonos_microfonos_pilas_reloj_delete_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reloj',
            old_name='nombreAReloj',
            new_name='nombreReloj',
        ),
    ]
