# Generated by Django 4.0.4 on 2022-07-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_solicitudes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitudes',
            new_name='Solicitud',
        ),
    ]
