# Generated by Django 4.0.4 on 2022-07-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='idsolicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
